kafka:
  default.topic.config:
    auto.offset.reset: "earliest"
  group: "kowalski"
  scala_version: "2.13"
  kafka_version: "3.4.1"
  bootstrap.servers: "0.0.0.0:9092"
  zookeeper: "0.0.0.0:2181"
  path: "kafka_2.13-3.4.1"
  public_host: